# Generated by Django 5.0.4 on 2024-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_item_categories_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='aaaa', upload_to='items/'),
            preserve_default=False,
        ),
    ]
